name: Update Infographics Workflow

on:
  workflow_dispatch:

jobs:
  update_infographics:
    name: Update Infographics with Latest Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deebo Samuel Receiving Infographic
        run: |
          cd notebooks/deebo_samuel_receiving
          jupyter nbconvert --to script deebo_samuel_receiving.ipynb
          python deebo_samuel_receiving.py
          mv deebo_samuel_receiving.png ../../infographics/

      - name: Jimmy Garoppolo Passing Infographic
        run: |
          cd notebooks/jimmy_garoppolo_passing
          jupyter nbconvert --to script jimmy_garoppolo_passing.ipynb
          python jimmy_garoppolo_passing.py
          mv jimmy_garoppolo_passing.png ../../infographics/

      - name: Third Down Penalties Infographic
        run: |
          cd notebooks/third_down_penalties
          jupyter nbconvert --to script third_down_penalties.ipynb
          python third_down_penalties.py
          mv third_down_penalties.png ../../infographics/

      - name: Second Half Stats Infographic
        run: |
          cd notebooks/second_half_stats/
          jupyter nbconvert --to script second_half_stats.ipynb
          python second_half_stats.py
          mv second_half_stats.png ../../infographics/

      - name: Commit and Push Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add infographics/
          git commit -m "Updated infographics on `date` with GitHub Actions"
          git push origin main
