name: Update Infographics Workflow

on:
  workflow_dispatch:

jobs:
  update_infographics:
    name: Update Infographics with Latest Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Passer Rankings ANY/A
        run: |
          cd notebooks/adjusted_net_yards_pts/
          jupyter nbconvert --to script adjusted_net_yards_pts.ipynb
          python adjusted_net_yards_pts.py
          mv adjusted_net_yards_pts.png ../../infographics/

      - name: Commit and Push Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add infographics/
          git commit -m "Updated infographics on `date` with GitHub Actions"
          git push origin main
