name: Update Infographics Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_infographics:
    name: Update Infographics with Latest Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Third Down Penalties Infographic
        run: |
          cd notebooks/third_down_penalties
          jupyter nbconvert --to script third_down_penalties.ipynb
          python third_down_penalties.py
          mv third_down_penalties.png ../../infographics/

      - name: Commit and Push Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add infographics/third_down_penalties.png
          git commit -m "Updated infographics on `date` with GitHub Actions"
          git push origin github_worklow_test